### PR TITLE
Feature/fetch content

### PR DESCRIPTION
**Pull request by Leon0402**
Hi there, 

as discussed the follow up pull request :) 

In contrast to the other patch, I just changed the things necessary to make this work nicely with FetchContent.
There should be made also improvements to the complete install logic, but contrary to the other repo, the cmake here is not in such a good shape (although quite a few things should be improved by this pull request). I think the effort to clean up the install logic and other stuff should better be made to integrate this repository into the other one.

### CODE REVIEW

**Comment by Leon0402** [comment]
Again it would be nice, if you could share the travis link, so I can have a look if everything is running fine

**Comment by rbock** [comment]
Wow, you're quick :-)

https://travis-ci.org/github/rbock/sqlpp11-connector-sqlite3/pull_requests

**Comment by Leon0402** [comment]
> Wow, you're quick :-)

It's good cmake practise for me!
And I want to try out the lib and I'm way to lazy to install dependencies ;)

**Comment by Leon0402** [comment]
Hi, 
I had some time today and fixed some bugs I found and the travis build is now working! 

I'm not sure though what the problem with the appVeyor build is, it seems unrelated to this pull request? Could you fix it possibly? 
I think the setup with AppVeyor could also be simplified now as the dependencies Date and Sqlpp11 are pulled in automatically and don't have to be installed on the machine. But I'm not familiar with how AppVeyor works.

**Comment by rbock** [comment]
Hi Leon,

AppVeyor scripts are essentially powershell scripts. The way I read the log, it seems like the `cd sqlpp11-connector-sqlite3` did not work.
Calling `dir` probably shows what is going on.

It would be great if you could adjust the script. I assume we could drop the `git clone` commands and related lines?

The only "magic" in the current script is around installing sqlite3. I did not find the real packages at the time. That's why the script is downloading binaries and include files (I would assume this is not necessary any more).

Thanks,

Roland

PS: I can try to look into it as well, but it will certainly take a couple of days to find the time.

**Comment by Leon0402** [comment]
hmm where is the appVeyor gone?

**Comment by rbock** [comment]
Thanks for diving right into it! The scripts are so much nicer now!

**Comment by Leon0402** [comment]
Hi Roland, you're welcome! 

I actually got it working already, but I wondered (just to be sure) if a failing test actually failed. Therfore I just changed the assert in Sqlpp11Sqlite3AttachTest. This works perfectly on my machine (the tests fails in seconds), but on the appVeyor it leads to a timeout. Do you have any idea why? Why isn't the test failing properly?

**Comment by rbock** [comment]
Hi Leon,

No, I don't know why the failure is timing out. My guess is that `assert` is not handled well for some reason.

I assume it would behave better, if we replaced it

- an error message and
- return non-zero

But this is merely a stab in the dark.

Best,

Roland

**Comment by Leon0402** [comment]
You could be right! Actually I saw that the travis build didn't even fail. 

For test purposes I changed the assert to 
```
  if (db(select(all_of(right)).from(right).unconditionally()).empty())
    return 1;
```
And both tests fail now (and quickly)

I don't have an explanation though, why it's a timeout with assert on AppVeyor and no fail on Travis at all as it's failing perfectly well on my machine. Would be really interested to know where the difference is. 

But I guess for now, this is ready to be merged (as soon as I have put back the assert). Perhaps we should update the tests at some point (possibly by using catch2 or googletest)

**Comment by rbock** [comment]
Strange that a failed assert does not even get identified as a failure on Travis? In that case, I would actually suggest to keep the "hand-crafted" version.

Looking through the changes I noticed the `Testing` files. I assume you added those by accident?

Re: catch2/googletest: Yes, it would make sense to update the tests. It would also make sense to test output more often. Currently many tests mainly check if the program runs without crashing (and the author reads the output to check if that looks reasonable).

**Comment by Leon0402** [comment]
Do you mean by hand-crafted the if() return 1 "solution" I used? I didn't want to change anything regarding the tests as it might is out of scope ... presumably other tests have problems as well. This was just one tests I randomly picked.

I suppose I did add the Testing files by accident, gonna remove them.

**Comment by rbock** [comment]
Good point, yes, let's keep the scope tight.

**Comment by rbock** [comment]
Merged. Thanks again! I'll let this sink in for a couple of days before tagging a new release.

**Pull request merged**
