### PR TITLE
Cmake enhancements

### PR DESCRIPTION
**Pull request by theodelrieu**
Hi!

After quite a lot of blood and tears, I managed to build/link against Sqlcipher/OpenSSL/Zlib.

I've tested on Windows only for now. Some things need to be cleaned up:

* Using cmake targets everywhere: HinnantDate, Sqlite3, Sqlpp11.
* Find a better way to deal with `sqlpp11-connector-sqlite3-dynamic`.

### CODE REVIEW

**Comment by rbock** [comment]
Thanks! Looks cleaner at first glance. Haven't looked in much detail yet, will do so asap. Travis seems to be happy with your changes :-)

I saw you added some export hints for MSVC. Just being curious: What's the impact, e.g. in terms of size, link time?

Assuming that you are going to clean the things you mentioned, I will wait before merging. OK?

**Comment by theodelrieu** [comment]
> Assuming that you are going to clean the things you mentioned, I will wait before merging. OK?

Sure, I also need to test on macOS and Linux at work with Sqlcipher/OpenSSL/Zlib first.

>What's the impact, e.g. in terms of size, link time?

Well the final `.exe` will be smaller, I'm not sure about the link times though. 
And clients have to define `BUILD_SHARED_LIBS=ON` to enable shared builds. Another thing I'll have to try on macOS and Linux.

**Comment by theodelrieu** [comment]
Unfortunately I didn't have time to continue the work on sqlpp11 so far, and the next weeks are most likely going to be the same. I'll let you know!

**Comment by rbock** [comment]
OK, then I'll wait for your feedback on Monday and if that looks good I'd merge.

**Comment by theodelrieu** [comment]
Just tried on both OS and it works :)

**Pull request merged**
