### PR TITLE
Added checks for TRIM(X)

### PR DESCRIPTION
**Pull request by juandent**
The checks are placed inside #ifdef JDH/#endif.

### CODE REVIEW

**Comment by rbock** [comment]
For some reason your change seems to have affected every single line? I guess there is some whitespace stuff going on...

We should wait until the pull request for sqlpp11 is done (looks pretty good already) and then add the new check without the ifdef.

**Comment by juandent** [comment]
Got it!

Regards
Juan

**Comment by juandent** [comment]
I think I know why the difference in every line: Windows end of lines are made up of CR/LF while Linux I believe uses only one character, right?
That would explain the dramatic apparent change!

**Comment by rbock** [comment]
That would explain it. Can you change your config for sqlpp-related edits? That would help a lot :-)

**Pull request closed without merging**
