### PR TITLE
missing bind for unsigned integral

### PR DESCRIPTION
**Pull request by MatthieuTexier**
Hello,
I wish to use unsigned integral type in field but bind_result_t::_bind_unsigned_integral_result is missing.
Best regards.
Matthieu

### CODE REVIEW

**Comment by rbock** [comment]
Hi Matthieu,

Thanks! Can you add a small test to show that the expected value range is actually working?

Meanwhile, I'll take a look at the travis configuration. It seems a bit outdated.

Best,

Roland

**Comment by rbock** [comment]
The travis configuration is update on develop and master.

When you update your pull request it should build completely.

**Comment by MatthieuTexier** [comment]
OK Roland, thanks.
I did wrote a test but it doesn't pass.
I can cast from int64_t in bind_result_t but I don't know where to cast to int64_t for storage.

**Comment by rbock** [comment]
Which storage do you mean? The datatype of unsigned_integral in sqlpp11 should be `uint64_t`.

**Comment by rbock** [comment]
Ping :-)

**Comment by Leon0402** [comment]
I think we can close this now :)

**Comment by rbock** [comment]
See #79

**Pull request closed without merging**
